### ISSUE TITLE
boot和root分区的大小能否修改

### ISSUE THREAD

**Issue by maxmib** [raysworld/onecloud-emmc-install#1]

**Comment by raysworld** [comment]
I think it would totally fine to set the size of boot and root partition to any number you like. Feel free to try :-)

**Comment by maxmib** [comment]
> I think it would totally fine to set the size of boot and root partition to any number you like. Feel free to try :-)

调整分区大小后写入Emmc会不能启动，不知道是不是和emmc上的分区有对应关系，或者和uboot的引导启动参数有对应关系
